version: '3.3'
services:

  inventory-db:
    container_name: inventory-db
    image: postgres:latest
    environment:
      POSTGRES_DB: inventory-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - rede-relatorios      
    ports:
      - "5432:5432"  

  relatorios:
      build: './relatorios'
      container_name: relatorios
      depends_on:
        - inventory-db
      networks:
        - rede-relatorios
      environment:
        - DB_HOST=inventory-db
        - DB_PORT=5432
        - DB_NAME=inventory-db
        - DB_USER=postgres
        - DB_PASSWORD=postgres        
      ports:
        - 8080:8080

networks:
  rede-relatorios:
    driver: bridge